### ISSUE TITLE
Update to latest CI admiral conventions

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralpeds#12]
(same for admiraltemplate)

**Comment by rossfarrugia** [comment]
Thanks @ahasoplakus for signing up to this issue! @dgrassellyb as discussed please can you work with Sukalpo to provide some guidance on this issue as needed.

**Comment by dgrassellyb** [comment]
Hi @ahasoplakus ! You can find here the link to `admiralci` documentation : https://pharmaverse.github.io/admiralci/index.html - and this specific section explains how to reuse existing `admiralci` workflows : https://pharmaverse.github.io/admiralci/index.html#reuse-recommended - I would start with this, and of course you can reach me if you have any issues !
