### ISSUE TITLE
General Issue: Recreate WHO growth chart data using code

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiralpeds#17]
### Background Information

From discussion #13:

```
For WHO, the reference data are at
https://www.who.int/toolkits/child-growth-standards/standards
You want to click on 'standards' and then on 'weight-for-age', length/height for age, BMI-for-age, or weight-for-length/height. And you want to look at the 'Expanded Tables' - this gives the L M S values by day of age.

One question with the WHO charts is whether people want to use weight-for-length or BMI-for age for infants. The official CDC guidance is to use weight-for-length, but this will result in some missing data for kids who have a length outside the range in the WHO data. There's a least 1 paper I know of that concludes that BMI-for-age is better, but I think the 2 metrics are very similar.
```

Recreate the data using `tribble()` for replicability as data source may change overtime and its easier to track than floating csv's
Use snapshots for testthat 

### Definition of Done

See how #15 was done
- [x] Render each necessary WHO dataset as specified above into an .rda object using `tibble::tribble()`
- [ ] Use `testthat::expect_snapshot()` so we can track changes in the feature

**Comment by ngiangre** [comment]
Just adding a helpful package for completing this issue: [datapasta](https://milesmcbain.github.io/datapasta/)

**Comment by Pierre-Wallet** [comment]
Hi @rossfarrugia @zdz2101, @CDC-DNPAO, 

I have a few questions 😀.

Regarding the metadata:
I noticed that the structure of WHO metadata is different from CDC. In WHO, there is one dataset per sex.
I would then keep this format and recreate the internal metadata as they are from the WHO website.
Is it ok to proceed this way?
I will propose a naming convention similar to Zelos.

Regarding the technical aspect:
I noticed Zelos created the programs that build the dataset in inst folder. It means that the end user will have access to it when installing the package. Is it something that we want or should we store these programs in a data-raw folder which is not accessible to the end user but only to the developer?

Thanks for your help!

**Comment by CDC-DNPAO** [comment]
Piere - you're right about the difference between the WHO and CDC reference
files.  I've always hated the separate WHO files for each sex because it
involved more downloading, but whatever you think is the best way to store
these files is absolutely fine with me.

It's hard for me to think that most people will actually want to see these
reference data files, but there might be some very unusual person who wants
to.  So if it's easy to make them available, it would be a good idea.
Honestly, they are available in my packages, but this is mostly because I
didn't know what I was doing when building a package.  I feel as if I've
learned R by reading StackOverflow answers!

David

**Comment by Pierre-Wallet** [comment]
Hi David,

my point was to discuss the access to the program that builds the reference data, not the data itself.
Of course the reference data will be available.

I am in favor of keeping all files separated to reflect exactly what is contained in the .xls files on the WHO site.
It is easier for any end-user to compare the initial source to what we store in the package.
Plus these reference dataset are the unique source of truth to start all the upcoming derivations.
Combining them increases the risk of making a handling mistake and the overall maintenance.
This is only my opinion and based on my current knowledge of this project.

**Comment by CDC-DNPAO** [comment]
OK - whatever you think is best is fine with me

david

**Comment by rossfarrugia** [comment]
> I am in favor of keeping all files separated to reflect exactly what is contained in the .xls files on the WHO site. 

Makes sense to me Pierre! In the rare chance they ever change then it would be easier to maintain as you say.

**Comment by ngiangre** [comment]
Glad that pkg was somewhat helpful! I have not used it myself - I just saw
it circulating on fosstodon :)

If you find a better approach let us know! What might be hard is knowing
when those files update. Maybe use the {fs} or {httr2} pkgs to see if the
files updated (e.g. time stamp)? Might be helpful so that we can
subsequently update the data in our package. If anything, maybe include a
test for this - we would then have to update our pkg accordingly if those
files were ever updated. Does this make sense?

Cheers,
Nick Giangreco, PhD
nickg.bio

**Comment by Pierre-Wallet** [comment]
@zdz2101 , @rossfarrugia 

having an issue with my PR that I do not really understand.
The roxygens comments seem to be aligned with .Rd files.
Any help is parreciated.
Thanks in advance.

Below is the issue from the pipeline:

D man/WHO_bmi_for_age_boys.Rd
 D man/WHO_bmi_for_age_girls.Rd
?? man/who_bmi_for_age_boys.Rd
?? man/who_bmi_for_age_girls.Rd
🙈 Manuals are not up-to-date with roxygen comments!
🔀 The following differences were noted:

💻 Please rerun the following command on your workstation and push your changes
--------------------------------------------------------------------
roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))
--------------------------------------------------------------------
ℹ roxygen2 version that was used in this workflow: ‘7.3.1’
🙏 Please ensure that the 'RoxygenNote' field in the DESCRIPTION file matches this version
Error: Process completed with exit code 1.

**Comment by zdz2101** [comment]
@Pierre-Wallet just run `devtools::document()` , commit and push the renaming of the .Rd files, the two you have pushed rn is capital WHO and the roxygenation turns it into lowercase

**Comment by Pierre-Wallet** [comment]
@zdz2101 ,
already done before , it does not change anything

**Comment by zdz2101** [comment]
weird, I pushed a commit for you, looks like its going through now, looks ready to review soon, just tag me once you think you're done

**Comment by Pierre-Wallet** [comment]
I do not really get what is happening because I did not do anything.
And now everything is in green! 
THanks for your help.

possible that there is a latency between the push and the pipeline run?

**Comment by rossfarrugia** [comment]
As discussed today @Pierre-Wallet will also add the head circumference metadata as part of this PR.
