### ISSUE TITLE
General Issue: Create test data initially within the admiralpeds repo

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralpeds#19]
### Background Information

See https://github.com/pharmaverse/admiralpeds/discussions/4 (i will leave this discussion open for now in case more tips come there, but please ensure you both follow it, then we can close it later).

Follow the guidance from https://pharmaverse.github.io/pharmaversesdtm/main/ as eventually we will move our test data out into this repo/package. If unsure of any conventions to follow, @manciniedoardo can advise.

Don't go overboard as this is only for driving the vignettes and templates so likely 5-10 patients DM and VS should be enough. Maybe you can split one each between you?

### Definition of Done

Some starter test data which we can build on over time, covering a range of ages so that we get a variety of derived values.

**Comment by rossfarrugia** [comment]
Or @sheramin @kabis-ops maybe 1 does first line and the other reviews the PR - please split as you see best

**Comment by kabis-ops** [comment]
Thanks @rossfarrugia . 
Hi Amin  (@sheramin) - how do you want to proceed? I am fine with either drafting the test data or reviewing them.

I agree with Ross, we should have examples for ~10 of patients in DM and VS.

- DM: I am thinking we should include partial dates of birth just for consideration when we will write the vignette? We should plan for patients <2 years and >=2 years old
- VS: 
- we should have values for Height/length, weight (BMI) and head circumference (?). 
- Values for VSTESTCD, as suggested by David 
> - For CDC values, we could use values from the 5th, (50th?) and 95th percentiles(https://github.com/pharmaverse/admiralpeds/discussions/4). For BMI, it would be good to add values for the extreme percentiles (P99_99 )
> - for WHO, we might want to pick values from SD4neg, SD4 or SD3neg, SD3
Please let me know your thoughts
Thanks

**Comment by sheramin** [comment]
> Thanks @rossfarrugia . Hi Amin (@sheramin) - how do you want to proceed? I am fine with either drafting the test data or reviewing them.
> 
> I agree with Ross, we should have examples for ~10 of patients in DM and VS.
> 
> * DM: I am thinking we should include partial dates of birth just for consideration when we will write the vignette? We should plan for patients <2 years and >=2 years old
> * VS:
> * we should have values for Height/length, weight (BMI) and head circumference (?).
> * Values for VSTESTCD, as suggested by David
> 
> > * For CDC values, we could use values from the 5th, (50th?) and 95th percentiles([What test data updates will we need in {pharmaversesdtm} for {admiralpeds}? See https://github.com/pharmaverse/pharmaversesdtm/issues/88 #4](https://github.com/pharmaverse/admiralpeds/discussions/4)). For BMI, it would be good to add values for the extreme percentiles (P99_99 )
> > * for WHO, we might want to pick values from SD4neg, SD4 or SD3neg, SD3
> >   Please let me know your thoughts
> >   Thanks

Hi Samia (@kabis-ops), I'm brand new to Admiral. You're probably familiar and experienced with Admiral, I'm ok if you take the lead and give me some todos like drafting the test datasets. Then, you review them. If this sounds good to you, please let me know where to start.

**Comment by rossfarrugia** [comment]
@sheramin as you're new, i would suggest the reverse. Let's have Samia do the first line here and you take on the review and testing. I often found testing to be the easiest first action to start with when I first started contributing. what do you think best @kabis-ops?

**Comment by kabis-ops** [comment]
ok I ll start drafting the test data. I let you know @sheramin when you can start reviewing them.
@CDC-DNPAO - would also appreciate if you could have a look at it too to see if this covers our need
Will keep you both posted when you can have a look

**Comment by CDC-DNPAO** [comment]
Sure - just let me know when I can take a look

David
