### ISSUE TITLE
Upload hex sticker for admiralpeds

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralpeds#2]
Upload hex sticker for admiralpeds @manciniedoardo do you have a copy?

**Comment by manciniedoardo** [comment]
Yes, [here it is](https://phuseaccount.sharepoint.com/:i:/r/sites/Pharmaverse-admiral/Shared%20Documents/admiral%20hex%20images/hex-admiralpeds.png?csf=1&web=1&e=AAuIqo)
