### ISSUE TITLE
General Issue: Remove non-ASCII characters in the package ahead of any release

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralpeds#46]
### Background Information

Non-ASCII characters cause NOTES to appear when running pre-release checks. We should remove any from the package to avoid any issues.

### Definition of Done

- Run the following in the searchbar on github:
 `repo:pharmaverse/admiralpeds /[^\x00-\x7F]+/`
- Remove anything flagged.

**Comment by sheramin** [comment]
Should they completely be removed or replaced with ASCII version where applicable? For example we can convert this format of double quote (“) with this (") which is ASCII compliant?

**Comment by rossfarrugia** [comment]
@sheramin replace where possible please, e.g. follow how done in this PR https://github.com/pharmaverse/admiral/pull/2457/files
