### ISSUE TITLE
Documentation:  Increase unit-test coverage for `derive_params_growth_height()`

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiralpeds#50]
Create unit tests for `derive_params_growth_height()` using the pre-existing WHO metadata, be sure to include:

- edge cases such as extremely low or high height/lenghts
- subject that is under and over 2 years old between visits
- missing height/lengths, insertion of values like NA
- regular/as expected height/lengths

**Comment by rossfarrugia** [comment]
@ahasoplakus please work on this issue with the target of having the PR reviewed and merged by end of the month as discussed last meet.
