### ISSUE TITLE
Documentation:  Increase unit-test coverage for `derive_params_growth_age()`

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiralpeds#51]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Create unit tests for `derive_params_growth_height()` using the pre-existing CDC/WHO metadata, be sure to include:

- tests for age-for-weight, age-for-height, age-for-bmi, age-for-head circumference
- test for extremely high/low values of each in the above
- for expected >= 95%-tile BMI, that the adjustment is properly made

**Comment by rossfarrugia** [comment]
@Minlei0201 i sent you an invite to join the admiralpeds dev team on GH so that you get write access to this repo. Once you have it then you can assign yourself to this issue. Please work on this with the target of having the PR reviewed and merged by end of the month as discussed last meet.
