### ISSUE TITLE
Documentation:  Suppress Package Messages in examples

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralpeds#58]
### Let us know where something needs a refresh or put your idea here!

https://pharmaverse.github.io/admiralpeds/dev/reference/derive_params_growth_age.html

![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/7e3447c2-890b-4ad8-968b-df98f082b185)

**Comment by rossfarrugia** [comment]
@pharmaverse/admiralpeds anyone want to take this one on and double check any other occurrences?

**Comment by sheramin** [comment]
> @pharmaverse/admiralpeds anyone want to take this one on and double check any other occurrences?

I found some occurrences in the following files:
https://github.com/pharmaverse/admiralpeds/blob/main/data-raw/adsl_peds.R, vs_peds.R and  dm_peds.R

I think `rlang` and `admiral` print similar messages too.

**Comment by santarabantoosoo** [comment]
should the suppress function be applied to all imports in all pages or only to the two functions facing the users as in the [reference page](https://pharmaverse.github.io/admiralpeds/dev/reference/index.html)?

**Comment by rossfarrugia** [comment]
@santarabantoosoo i would agree only needed for those user-facing in the reference page so i think the test data scripts can be left.
