### ISSUE TITLE
ADVS template: add interpolation functions

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralpeds#62]
In our ADVS template we should update the reference files with the interpolated rows so the CDC charts (>=2 yrs old) would be by day then, just like the WHO charts. The rationale for this is we already currently massage the reference files in our template, e.g. converting the CDC months into days to be more consistent with WHO charts. So this way our package still contains the raw files from CDC, but we show the users complete transparency of how we update these to make them into the metadata we pass into our function. Then if a user ever wants to simplify and remove the interpolation then they could just delete the block of code that we’d add to the template to do this. 

The interpolation will require 2 new R functions to be added to our package (one for BMI incl P95 & Sigma, and one for the other parameters without this). These 2 functions can then be called in the template Metadata section.

David has provided example code here but we should try to re-write this using tidyverse packages (preferably keeping our package dependencies lean as possible) and not data.table, and we should match the admiraldev conventions.

**Comment by Fanny-Gautier** [comment]
@rossfarrugia I can get the same values as David only if I round the age in days as done in below screenshot and as done in David's code.
![image](https://github.com/pharmaverse/admiralpeds/assets/157114584/1ff47eed-6075-444a-869d-cf8cfa17559b)
Could you please confirm whether this approach is to be applied in our ADVS template ? If yes, I think this needs to be described in the vignette.

I am currently checking why I get duplicates on the age of 730 days while rounding it - knowing that the first record is not as per David's data.
![image](https://github.com/pharmaverse/admiralpeds/assets/157114584/8bd88bc3-9d45-451a-9a29-ef54b1f29885)

**Comment by Fanny-Gautier** [comment]
The first record is from the WHO data, while the second record is from the interpolated CDC data.
![image](https://github.com/pharmaverse/admiralpeds/assets/157114584/c42ff06c-268b-485e-9f6f-6edb5714bd35)

Could you please confirm that we should drop the second record and keep only the interpolated CDC data where AGE in Days is >= 730.5 days ?

**Comment by rossfarrugia** [comment]
Thanks @Fanny-Gautier for all the thorough checks!

On the rounding point, yes it seems rational to me as we’re trying to get the CDC metadata to be by day here just like the WHO metadata. So rounding seems sensible to me and agree there should only be one day 730. If we are matching David’s results then I feel confident given his greater expertise in this area. I'll add a note to the vignette to explain the rounding, as you requested.

For the duplicate records, I agree with your suggestion above as in the vignette we say we only use CDC growth chart for >=730.5 days.

**Comment by Fanny-Gautier** [comment]
Hi @rossfarrugia ,
I think it is now completed from my end. Could you please run devtools::document() in order to update NAMESPACE ? the technical issue from Cytel system is still not fixed... Thanks.

**Comment by rossfarrugia** [comment]
> Hi @rossfarrugia , I think it is now completed from my end. Could you please run devtools::document() in order to update NAMESPACE ? the technical issue from Cytel system is still not fixed... Thanks.

Done @Fanny-Gautier - feel free to make a PR and tag me and Zelos for review whenever you think ready.

**Comment by rossfarrugia** [comment]
@Fanny-Gautier FYI i'm just going to make one extra commit for a few minor clean ups i spotted after building the site, in order to make the reference page more consistent with Zelos's functions.

**Comment by rossfarrugia** [comment]
@Fanny-Gautier please double check the commits i made before you make the PR to check you're happy. They were all updates related to `devtools::document()`, `devtools::check()` or to make the roxygen2 section more consistent with Zelos's functions.

**Comment by rossfarrugia** [comment]
no problem - let me know when done and i can rerun `devtools::document()` again then

**Comment by Fanny-Gautier** [comment]
@rossfarrugia it's now updated. could you please re-run `devtools::document()`. Once done I'll create the PR. Thanks

**Comment by rossfarrugia** [comment]
Done @Fanny-Gautier
