### ISSUE TITLE
Use consistent wording in package for sex rather than gender

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralpeds#64]
Review feedback comment from Edoardo:

_As there is no distinction between the words "Sex" and "Gender" I would suggest sticking to "Sex" across the whole package (code + documentation) as it is also the ADaM variable name._ 

Can we make this consistent across our package? @santarabantoosoo would be great if you could take this one.

**Comment by santarabantoosoo** [comment]
Sure
