### ISSUE TITLE
General Issue: Ben's sporadic review

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralpeds#66]
### Background Information

I don't understand why admiral is in parentheses?  It looks confusing to me?  Is this how it is done in other extensions? 
![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/973b2e74-b48a-46b1-912f-6d555f42fe05)

Make this a link - it will never change 
![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/b0121818-f6d9-4e78-88a0-20aa7b47dffd)

What about a note on future templates that are coming and asking commmunity to fill out an issue if they think one might be handy 
![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/1c30c026-e136-431e-8b71-605db7bdcb0a)

These roxygen comments seem to have come through - I think you can do `#' #` 
![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/e3bdbdaf-d526-4e35-86ce-46c5c551e25c)
 
 Can these be made into regular quotes `"` this has caused us issues with CRAN 
 
![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/095cd2e3-bf8c-4f89-8e15-686b9dfb7e06)

What is updated
![image](https://github.com/pharmaverse/admiralpeds/assets/10111024/daf5b97e-1761-4c27-a98e-0d48f699ef01)

**Comment by bms63** [comment]
I had a little bit of time to do a quick glance!  Just some formatting notes.  Looks so cool!!!

**Comment by rossfarrugia** [comment]
Thanks @bms63 for the review!

First couple of points are same in other pkg exts like admiralonco so won't update here as else I need to do the same in many other places.

For the point on templates, ADVS seems to be the main pediatric specific source of differences in ADaM. We don't yet know of any other areas of major impact. We can ask community for input and future ideas though after first release. I like that idea - FYI @Fanny-Gautier 

I'll fix the others all in an existing PR I'm working on.
