### ISSUE TITLE
General Issue: Improve `derive_interp_records()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralpeds#73]
### Background Information

- The final dataset shouldn't be assigned to a variable. Then the returned dataset is printed. At the moment we get:
   ```
    > derive_interp_records(my_cdc, by_vars = exprs(SEX), parameter = "HEIGHT")
    > 
    ```
    Then also the example in the documentation could be simplified to
    ```
    library(dplyr, warn.conflicts = FALSE)
    library(rlang)

    admiralpeds::cdc_htage %>%
      mutate(
        SEX = case_when(
          SEX == 1 ~ "M",
          SEX == 2 ~ "F",
          TRUE ~ NA_character_
        ),
        # Ensure first that Age unit is "DAYS"
        AGE = round(AGE * 30.4375)
      ) %>%
      # Interpolate the AGE by SEX
      derive_interp_records(
        by_vars = exprs(SEX),
        parameter = "HEIGHT"
      )
    ```
- The function drops variables which are not expected. `derive_*()` functions shouldn't drop any variables or records.
- Why is the uniqueness of records only checked if `by_vars` is `NULL`? I wonder if the check should be replaced by calling `signal_duplicate_records(dataset, by_vars = exprs(!!!by_vars, AGE))` regardless of the value of `by_vars`.
- In the documentation of the `dataset` argument `AGEU` is listed as required variable. However, this isn't checked nor is the variable used in the code.
- The "Value" section of the documentation should provide more details. I had to read the code to understand what the function is doing. For example it should be stated that _linear_ interpolation is done and that the output dataset contains a record for each day from the minimum age to the maximum age.

**Comment by rossfarrugia** [comment]
thanks Stefan!

@Fanny-Gautier please can you consider these comments and make updates in a new branch/PR if you agree

**Comment by Fanny-Gautier** [comment]
Unit tests are now failing since keeping potential extra variables: I have to re-work on it. Will try to complete them by tomorrow.
