### ISSUE TITLE
Error while `building_site()` in `build_article()` exactly

### ISSUE THREAD

**Issue by Fanny-Gautier** [pharmaverse/admiralpeds#98]
### Background Information

Reviewing Remi's PR I face the following error while building the site.
![image](https://github.com/user-attachments/assets/121b22ad-7743-4051-9e8d-47d007407cc1)

I could not find where it comes from: I tried both on Remi's branch and on `main` branch.
`staged_dependencies.yaml` well includes `pharmaversesdtm` ,
`DESCRIPTION` also includes `Suggests: pharmaversesdtm`
I am wondering what is missing, and whether this is missing from `NAMESPACE`?

**Comment by rossfarrugia** [comment]
@Fanny-Gautier I wonder if its to do with the following that I think @zdz2101 may have accidentally left in `DESCRIPTION`:

```
Remotes: 
    pharmaverse/pharmaversesdtm@admiralpeds_data_migration
```

Remove that and try.

**Comment by Fanny-Gautier** [comment]
> @Fanny-Gautier I wonder if its to do with the following that I think @zdz2101 may have accidentally left in `DESCRIPTION`:
> 
> ```
> Remotes: 
>     pharmaverse/pharmaversesdtm@admiralpeds_data_migration
> ```
> 
> Remove that and try.

Thanks @rossfarrugia, I'll try it again today with a fresh session and let you know if I still face the error. Thanks

**Comment by Fanny-Gautier** [comment]
> @Fanny-Gautier I wonder if its to do with the following that I think @zdz2101 may have accidentally left in `DESCRIPTION`:
> 
> ```
> Remotes: 
>     pharmaverse/pharmaversesdtm@admiralpeds_data_migration
> ```
> 
> Remove that and try.

I tried again by removing
`Remotes: 
    pharmaverse/pharmaversesdtm@admiralpeds_data_migration` but I still face the error.

**Comment by zdz2101** [comment]
Try adding (>= 1.1.0) in the description for `pharmaversesdtm` the export of the peds dataset only exists as of that newest deployment, and make sure your local `pharmaversesdtm` is up to date

**Comment by Fanny-Gautier** [comment]
> Try adding (>= 1.1.0) in the description for `pharmaversesdtm` the export of the peds dataset only exists as of that newest deployment, and make sure your local `pharmaversesdtm` is up to date

Thanks @zdz2101. I indeed tried that as well last Wednesday, but you are right, `pharmaversesdtm` wasn't locally updated... it's now working fine while locally updated. Thank you.
